#Spare LVDS inputs
set_property IOSTANDARD LVCMOS33 [get_ports {LVDS_spare_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LVDS_spare_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LVDS_spare_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LVDS_spare_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LVDS_spare_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LVDS_spare_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LVDS_spare_in[0]}]
set_property PACKAGE_PIN D20 [get_ports {LVDS_spare_in[0]}]
set_property PACKAGE_PIN F16 [get_ports {LVDS_spare_in[1]}]
set_property PACKAGE_PIN F17 [get_ports {LVDS_spare_in[2]}]
set_property PACKAGE_PIN J15 [get_ports {LVDS_spare_in[3]}]
set_property PACKAGE_PIN B19 [get_ports {LVDS_spare_in[4]}]
set_property PACKAGE_PIN A20 [get_ports {LVDS_spare_in[5]}]
set_property PACKAGE_PIN D19 [get_ports {LVDS_spare_in[6]}]
